# This script generates mafia_bot.py
import json, os

def W(s=""): lines.append(s)

lines = []
W('import os, sys, random, logging, asyncio, json, time')
W('from typing import Dict')
W('sys.path.insert(0, r"D:\\pylibs")')
W('from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup')
W('from telegram.ext import Application, CommandHandler, ContextTypes, CallbackQueryHandler, MessageHandler, filters')
W()
W("TOKEN = os.getenv('BOT_TOKEN', '8388604050:AAFLH3sa6kIbg3YuuiLGMp1VBJT0JT2X9vg')")
W("MAX_PLAYERS = 40; DEFAULT_NIGHT = 30; DEFAULT_VOTE = 30")
W("NIGHT_GIF = 'BQACAgIAAxkBAAOoag8GAhuRN1n13dquB5-1trg6dVYAApOiAAKZ6IFIO8rY5Yz9VEU7BA'")
W("DAY_GIF = 'BQACAgIAAxkBAAOpag8GBuyutTcDWHvrj17Rfu7NIBwAApSiAAKZ6IFIkFcNCmuX2Wg7BA'")
W("STATS_FILE = os.path.join(os.path.dirname(__file__), 'stats.json')")
W("PROFILES_FILE = os.path.join(os.path.dirname(__file__), 'profiles.json')")
W("CARD_NUMBER = '4073-4200-7154-7032'; ADMIN_ID = 7820231987")
W("logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')")
W("games: Dict[int, 'MafiaGame'] = {}; user_game: Dict[int, int] = {}")
W("ghosts: Dict[int, set] = {}; settings_chats: Dict[int, dict] = {}; pending_checks: Dict[int, dict] = {}")
W("GAME_MODES = {'classic': 'Classic', 'full': 'Full'}")
W()

# Profile system
W("def load_profiles():")
W("    try:")
W("        with open(PROFILES_FILE, encoding='utf-8') as f: d = json.load(f)")
W("    except: return {}")
W("    changed = False")
W("    for k, v in d.items():")
W("        if 'items' not in v: v['items'] = {}; changed = True")
W("        for it in ['shield','kill_protect','vote_protect','rifle','mask','fake_doc']:")
W("            if it in v['items'] and isinstance(v['items'][it], int):")
W("                v['items'][it] = {'count': v['items'][it], 'active': True}; changed = True")
W("            if it not in v['items']: v['items'][it] = {'count': 0, 'active': True}; changed = True")
W("        for fld in ['hero','hero_attack','hero_defense']:")
W("            if fld not in v: v[fld] = (False if fld == 'hero' else 0); changed = True")
W("        for fld in ['dollars','olmos','evro','games','wins','losses']:")
W("            if fld not in v: v[fld] = 0; changed = True")
W("        if 'bought_role' not in v: v['bought_role'] = None; changed = True")
W("    if changed: save_profiles(d)")
W("    return d")
W()
W("def save_profiles(data):")
W("    with open(PROFILES_FILE, 'w', encoding='utf-8') as f: json.dump(data, f, indent=2, ensure_ascii=False)")
W()
W("def get_profile(uid, name=None):")
W("    d = load_profiles(); k = str(uid)")
W("    if k not in d:")
W("        d[k] = {'name': name or str(uid), 'dollars': 0, 'olmos': 0, 'evro': 0,")
W("                'items': {it: {'count': 0, 'active': True} for it in ['shield','kill_protect','vote_protect','rifle','mask','fake_doc']},")
W("                'games': 0, 'wins': 0, 'losses': 0, 'bought_role': None,")
W("                'hero': False, 'hero_attack': 0, 'hero_defense': 0}")
W("        save_profiles(d)")
W("    elif name and d[k]['name'] == str(uid): d[k]['name'] = name; save_profiles(d)")
W("    return d[k]")
W()
W("def save_profile(uid, data):")
W("    d = load_profiles(); d[str(uid)] = data; save_profiles(d)")
W()
W("def has_item(uid, item):")
W("    d = load_profiles(); k = str(uid)")
W("    return k in d and d[k].get('items', {}).get(item, {}).get('count', 0) > 0 and d[k]['items'].get(item, {}).get('active', False)")
W()
W("def remove_item(uid, item, count=1):")
W("    d = load_profiles(); k = str(uid)")
W("    if k in d and d[k].get('items', {}).get(item, {}).get('count', 0) >= count:")
W("        d[k]['items'][item]['count'] -= count; save_profiles(d); return True")
W("    return False")
W()
W("def add_item(uid, item, count=1):")
W("    d = load_profiles(); k = str(uid)")
W("    if k in d:")
W("        if item not in d[k]['items']: d[k]['items'][item] = {'count': 0, 'active': True}")
W("        d[k]['items'][item]['count'] += count; save_profiles(d)")
W()
W("def toggle_item(uid, item):")
W("    d = load_profiles(); k = str(uid)")
W("    if k in d and item in d[k]['items']:")
W("        d[k]['items'][item]['active'] = not d[k]['items'][item]['active']")
W("        save_profiles(d); return d[k]['items'][item]['active']")
W("    return False")
W()
W("def add_olmos(uid, amount):")
W("    d = load_profiles(); k = str(uid)")
W("    if k in d: d[k]['olmos'] = d[k].get('olmos', 0) + amount; save_profiles(d)")
W()
W("def spend_olmos(uid, amount):")
W("    d = load_profiles(); k = str(uid)")
W("    if k in d and d[k].get('olmos', 0) >= amount:")
W("        d[k]['olmos'] -= amount; save_profiles(d); return True")
W("    return False")
W()

# Game classes
W("async def is_admin(chat, user_id, context):")
W("    try:")
W("        m = await context.bot.get_chat_member(chat.id, user_id)")
W("        return m.status in ('administrator', 'creator')")
W("    except: return False")
W()
W("def get_set(chat_id):")
W("    if chat_id not in settings_chats:")
W("        settings_chats[chat_id] = {'min': 1, 'night': DEFAULT_NIGHT, 'vote': DEFAULT_VOTE, 'mode': 'classic'}")
W("    return settings_chats[chat_id]")
W()

W("class Player:")
W("    def __init__(self, user_id, first_name, username=None):")
W("        self.user_id = user_id; self.first_name = first_name; self.username = username")
W("        self.role = None; self.alive = True; self.lover = None; self.defended = False")
W("        self.guard_target = None; self.blocked = False; self.team = 'village'")
W("        self.actions_used = {}; self.hero = False")
W("    @property")
W("    def display(self): return f'@{self.username}' if self.username else self.first_name")
W("    @property")
W("    def name(self): return self.display")
W()

W("class MafiaGame:")
W("    def __init__(self, chat_id, mode='classic'):")
W("        self.chat_id = chat_id; self.mode = mode")
W("        self.players: Dict[int, Player] = {}; self.phase = 'registration'; self.day = 0")
W("        self.votes: Dict[int, int] = {}; self.actions = {}; self.used_actions = {}; self.action_ready = {}")
W("        self.maniac_present = False; self.mine_target = None; self.sniper_targets = {}")
W("        self.watch_results = {}; self.chemist_target = None; self.fan_targets = {}")
W("        self.chameleon_targets = {}; self.drunk_targets = {}; self.teacher_targets = {}")
W("        self.seller_targets = {}; self.blocked_players = set(); self.rifle_uses: Dict[int, int] = {}")
W("    @property")
W("    def alive_players(self): return [p for p in self.players.values() if p.alive]")
W("    @property")
W("    def mafia_alive(self): return [p for p in self.players.values() if p.role in ('Don', 'Mafia') and p.alive]")
W("    def get_player(self, uid): return self.players.get(uid)")
W("    def alive_count(self): return len(self.alive_players)")
W()

W("ROLE_ICON = {")
W("    'Don': chr(0x1F974), 'Mafia': chr(0x1F974)+chr(0x1F3FC),")
W("    'Shifokor': chr(0x1F469)+chr(0x200D)+chr(0x2695)+chr(0xFE0F),")
W("    'Komissar': chr(0x1F575)+chr(0xFE0F), 'Manyak': chr(0x1F5E1)+chr(0xFE0F),")
W("    'Daydi': chr(0x1F9D9), 'Advokat': chr(0x1F9D1)+chr(0x200D)+chr(0x2696)+chr(0xFE0F),")
W("    'Bodyguard': chr(0x1F6E1)+chr(0xFE0F), 'Oshiq': chr(0x1F491),")
W("    'Kamikaze': chr(0x1F4A3), 'Tinch aholi': chr(0x1F9CD),")
W("    'Mashuqa': chr(0x1F483), 'Serjant': chr(0x1F46E)+chr(0x200D)+chr(0x2642)+chr(0xFE0F),")
W("    'Buqalamun': chr(0x1F98E), 'Omadli': chr(0x1F91E), 'Aferist': chr(0x1F939),")
W("    'Sehrgar': chr(0x1F9D9)+chr(0x200D)+chr(0x2642)+chr(0xFE0F),")
W("    'Suidsid': chr(0x1F9CC), 'Don xotini': chr(0x1F470)+chr(0x200D)+chr(0x2640)+chr(0xFE0F),")
W("    'Kimyogar': chr(0x1F468)+chr(0x200D)+chr(0x1F52C), 'Sotuvchi': chr(0x1F381),")
W("    'Tentak': chr(0x1F472), 'Oqituvchi': chr(0x1F468)+chr(0x200D)+chr(0x1F3EB),")
W("    'Muxlis': chr(0x1F52E), 'Minior': chr(0x2620)+chr(0xFE0F),")
W("    'Mergan': chr(0x1F3A4), 'Majnun': chr(0x1F57A), 'Ubica': chr(0x1F978),")
W("}")
W()
W("ROLE_DISPLAY = {")
W("    'Don': 'Don', 'Mafia': 'Mafiya', 'Shifokor': 'Shifokor', 'Komissar': 'Komissar',")
W("    'Manyak': 'Manyak', 'Daydi': 'Daydi', 'Advokat': 'Advokat', 'Bodyguard': 'Tansoqchi',")
W("    'Oshiq': 'Oshiq', 'Kamikaze': 'Kamikaze', 'Tinch aholi': 'Tinch aholi',")
W("    'Mashuqa': 'Mashuqa', 'Serjant': 'Serjant', 'Buqalamun': 'Buqalamun',")
W("    'Omadli': 'Omadli', 'Aferist': 'Aferist', 'Sehrgar': 'Sehrgar',")
W("    'Suidsid': 'Suitsid', 'Don xotini': \"Donning xotini\", 'Kimyogar': 'Kimyogar',")
W("    'Sotuvchi': 'Sotuvchi', 'Tentak': 'Tentak', 'Oqituvchi': 'Oqituvchi',")
W("    'Muxlis': 'Muxlis', 'Minior': 'Minior', 'Mergan': 'Mergan (Snayper)',")
W("    'Majnun': 'Majnun', 'Ubica': 'Ubica',")
W("}")
W()
W("MODE_ROLES = {")
W("    'classic': ['Don','Mafia','Shifokor','Komissar','Manyak','Advokat','Daydi','Kamikaze','Mashuqa','Serjant','Suidsid','Tinch aholi'],")
W("    'full': ['Don','Mafia','Shifokor','Daydi','Komissar','Kamikaze','Mashuqa','Serjant','Aferist','Tentak','Advokat','Don xotini','Kimyogar','Sotuvchi','Suidsid','Muxlis','Manyak','Minior','Mergan','Majnun','Buqalamun','Oqituvchi','Tinch aholi'],")
W("}")
W()

ROLE_PRICES = {
    "Tinch aholi": 100, "Shifokor": 300, "Daydi": 400, "Komissar": 500,
    "Kamikaze": 350, "Mashuqa": 450, "Serjant": 400, "Oqituvchi": 600,
    "Tentak": 500, "Muxlis": 350, "Advokat": 400, "Don xotini": 550,
    "Kimyogar": 600, "Sotuvchi": 700, "Suidsid": 650, "Manyak": 750,
    "Minior": 700, "Mergan": 800, "Buqalamun": 650, "Majnun": 550,
    "Aferist": 600, "Sehrgar": 900, "Ubica": 1000, "Don": 1200, "Mafia": 800,
}

W("ROLE_PRICES = {")
for k, v in ROLE_PRICES.items():
    W(f"    '{k}': {v},")
W("}")
W()

# Helper functions
W("def fmt_player(p):")
W("    return f'<a href=\"tg://user?id={p.user_id}\">{p.display}</a>'")
W()
W("def role_counts(game):")
W("    counts = {}")
W("    for p in game.alive_players: counts[p.role] = counts.get(p.role, 0) + 1")
W("    return ', '.join(f\"{ROLE_ICON.get(r,'')} {ROLE_DISPLAY.get(r,r)}\" + (f' - {c}' if c > 1 else '') for r, c in sorted(counts.items()))")
W()
W("def make_kb(player_ids, action, icons=False):")
W("    kb = []; row = []; lookup = {}; roles_d = {}")
W("    for g in games.values():")
W("        for pid, p in g.players.items(): lookup[pid] = p.display; roles_d[pid] = p.role")
W("    for i, pid in enumerate(player_ids):")
W("        name = lookup.get(pid, '?')")
W("        if icons and pid in roles_d: name = f'{ROLE_ICON.get(roles_d[pid],\"\")} {name}'")
W("        row.append(InlineKeyboardButton(name, callback_data=f'{action}:{pid}'))")
W("        if len(row) == 2: kb.append(row); row = []")
W("    if row: kb.append(row)")
W("    return InlineKeyboardMarkup(kb)")
W()

# Complete the file
result = '\n'.join(lines)
with open(r'C:\Users\RZ\Desktop\3D\mafia_bot.py', 'w', encoding='utf-8') as f:
    f.write(result)
fpath = r'C:\Users\RZ\Desktop\3D\mafia_bot.py'
print(f'Generated: {len(lines)} lines, {os.path.getsize(fpath)} bytes')
